# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check / Lint

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  setup-python:
    env:
      WORKON_HOME: ~/.venv
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name:  Install pipenv
      run: |
        python -m pip install --upgrade pipenv
    - name: Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.venv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
         pipenv sync --dev
    - name:  check cache
      run: |
        ls -latr ~/.venv

  lint_and_run_unit_tests:
    env:
      WORKON_HOME: ~/.venv
    runs-on: ubuntu-latest
    needs: setup-python
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run pytest tests/